### ISSUE TITLE
Fastq data availablity?

### ISSUE THREAD

**Issue by phylars** [isaisg/helperless#1]
Hi @isaisg,

Greetings. Really appreciate for you high-quality data. May I learn if the fastq data released somewhere? It is very good for you to directly provide the read count for convenience, but I wish to learn some alternative spilcing information from the all the avirulent bacteria treat Col-0 plant, which is not available in your read results, so I really need to run your fastq by Salmon. Could you please tell me where I can find the raw fastq file?

Thank you,

**Comment by isaisg** [comment]
Hello @phylars 

Yes. The FASTQ files were deposited on GEO repository under series id GSE151885 https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE151885

Thank you
